apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "components.oda.tmforum.org"
spec:
  scope: "Namespaced"
  group: "oda.tmforum.org"
  names:
    plural: "components"
    singular: "component"
    kind: "component"
  conversion:
    strategy: Webhook
    # webhookClientConfig is required when strategy is `Webhook` and it configures the webhook endpoint to be called by API server.
    webhook:
      conversionReviewVersions: ["v1alpha1", "v1alpha2", "v1alpha3", "v1beta1"]
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EUXlNakE0TkRBeE9Gb1hEVE14TURReU1EQTROREF4T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2FHCkp1QVRsZTUrTzJoNGdORWpROGhjQmRRR0hnQ0Exay9COXBkbmxzOHh0eVJ2TWFHWHR6VXdiRExDNmpiSUNsVWQKN0FLL0RkOVVBWTdLTnI4ZCtGM09WWHphaFhsSENQSllHRGtsOVZiVWNzL0JRbGZKY0FvYmxBUnhLWUdXdHh3QQoyNUZaMjRmeW0rcnpCb3d2YjdOVjdmZG04ZGR4Ny9ONVlodXZwVnhJbU9wTnFnR3hOdnFQV1ZTbkZoZXJPSEJvClFSTks0VFdVZnFmTytLdUhYM1U1UlNvNXZVbGdtaFNydFNKOVY3TUtTQnczR2x2d2xXSzdqRmRCQVpXNVBFQmQKRzlNN3E0M3dQaUcxOUd3cHhiNVlTSnVlck5ZdFlNcmlSVTI2MlNtemZHRUpVRnN3VTl5QnFoQjBJWXAwaTBJQQptb2lrdGNtSE5VSlQ0SUt2UEYwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZEVnpoc0xPTUtTME5kYzlGS2NrRzU2MTg4WUFNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCNE9aY2haWUlHc2MyWWdGRWFtTDdLdlV6cjVQUnMvdDFsdUtjdmFqNDdDR0pxY3VtVwo4UjF1NVdPaU56WXp4M0pyUkdyM2N0RmpxVngyU1ZtZTBOTGdCZWZNYmVhaFFObkVjWUs0TGMyL1ZFSitDZlJICktOSzhzTGpHbFlncGQxQlE1cTd6VmlpWUN6UldxR3A4djRzM2lSZ21OR1QvOXRmNGU1UVBQaG5ib2VKL0JjVVYKVlYyV2pucDdlWHJUN3pYNTd4WEZZZm1zQmZBZVAxZzM4RjJLVVFaTElPUmprR1JJMDBhVS9zc1BhcVhRQnUxbQpOcllOMDlkR1VlRlhyQzFvMHAxRjRBTFpxcFZ5ZFI5YTZheXVSMkY2QmpuZDkxbThhQ0E0OVdacDkweGRJQXlXCkZFc1RpbmJ4c0NOM3BrNndTM0dWczU2UDNXUGt6Rkh0M3lVWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        service:
          namespace: canvas
          name: compcrdwebhook
          path: /
          port: 443
  versions: 
  - name: "v1alpha1"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: false
    deprecated: true
    deprecationWarning: "oda.tmforum.org/v1alpha1 Component is deprecated; Please upgrade to oda.tmforum.org/v1alpha3 see https://github.com/tmforum-oda/oda-canvas-charts/issues/19"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:     
              coreFunction:
                type: object  
                properties:  
                  exposedAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        implementation:
                          type: string
                        path:
                          type: string
                        developerUI:
                          type: string
                        port:
                          type: integer
                  dependantAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        path:
                          type: string
              eventNotification:
                type: object  
                properties:  
                  publishedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
                  subscribedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
              management:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    href:
                      type: string
                    specification:
                      type: string
              security:
                type: object  
                properties:
                  securitySchemes: 
                    type: object
                    x-kubernetes-preserve-unknown-fields: true                        
              version:
                type: string
              description:
                type: string
              type:
                type: string
              selector:
                type: object
                x-kubernetes-preserve-unknown-fields: true    
              componentKinds:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              maintainers:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              owners:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true    
    additionalPrinterColumns:
    - name: exposed_APIs
      type: string
      description: list the endpoints for exposed APIs
      jsonPath: .status.summary/status.exposedAPIsummary
    - name: developer_UI
      type: string
      description: list the Developer User Interface(s)
      jsonPath: .status.summary/status.developerUIsummary
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.summary/status.deployment_status
  - name: "v1alpha2"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: false
    # deprecated: false
    # deprecationWarning: "oda.tmforum.org/v1alpha1 Component is deprecated; Please upgrade to oda.tmforum.org/v1alpha2 see https://github.com/tmforum-oda/oda-canvas-charts/issues/9"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:     
              coreFunction:
                type: object  
                properties:  
                  exposedAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        implementation:
                          type: string
                        path:
                          type: string
                        developerUI:
                          type: string
                        port:
                          type: integer
                  dependantAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        path:
                          type: string
              eventNotification:
                type: object  
                properties:  
                  publishedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
                  subscribedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
              management:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    href:
                      type: string
                    specification:
                      type: string
              security:
                type: object  
                properties:  
                  securitySchemes: 
                    type: object
                    x-kubernetes-preserve-unknown-fields: true    
                  partyrole:
                    type: object
                    properties:
                      specification:
                        type: string
                      implementation:
                        type: string
                      path:
                        type: string
                      developerUI:
                        type: string
                      port:
                        type: integer                
              version:
                type: string
              description:
                type: string
              type:
                type: string
              selector:
                type: object
                x-kubernetes-preserve-unknown-fields: true    
              componentKinds:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              maintainers:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              owners:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true    
    additionalPrinterColumns:
    - name: exposed_APIs
      type: string
      description: list the endpoints for exposed APIs
      jsonPath: .status.summary/status.exposedAPIsummary
    - name: developer_UI
      type: string
      description: list the Developer User Interface(s)
      jsonPath: .status.summary/status.developerUIsummary
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.summary/status.deployment_status
  - name: "v1alpha3"
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    # deprecated: false
    # deprecationWarning: "oda.tmforum.org/v1alpha1 Component is deprecated; Please upgrade to oda.tmforum.org/v1alpha2 see https://github.com/tmforum-oda/oda-canvas-charts/issues/9"
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:     
              coreFunction:
                type: object  
                properties:  
                  exposedAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        implementation:
                          type: string
                        path:
                          type: string
                        developerUI:
                          type: string
                        port:
                          type: integer
                  dependentAPIs:   
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        specification:
                          type: string
                        path:
                          type: string
              eventNotification:
                type: object  
                properties:  
                  publishedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
                  subscribedEvents: 
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        href:
                          type: string
              management:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    href:
                      type: string
                    specification:
                      type: string
              security:
                type: object  
                properties:  
                  securitySchemes: 
                    type: object
                    x-kubernetes-preserve-unknown-fields: true    
                  partyrole:
                    type: object
                    properties:
                      specification:
                        type: string
                      implementation:
                        type: string
                      path:
                        type: string
                      developerUI:
                        type: string
                      port:
                        type: integer   
                  controllerRole:
                    type: string             
              version:
                type: string
              description:
                type: string
              type:
                type: string
              selector:
                type: object
                x-kubernetes-preserve-unknown-fields: true    
              componentKinds:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              maintainers:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
              owners:
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true    
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true    
    additionalPrinterColumns:
    - name: exposed_APIs
      type: string
      description: list the endpoints for exposed APIs
      jsonPath: .status.summary/status.exposedAPIsummary
    - name: developer_UI
      type: string
      description: list the Developer User Interface(s)
      jsonPath: .status.summary/status.developerUIsummary
    - name: deployment_status
      type: string
      description: Deployment status [in progress, complete, failed]
      jsonPath: .status.summary/status.deployment_status
