apiVersion: apps/v1
kind: Deployment
metadata:
  name: compcrdwebhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compcrdwebhook
  template:
    metadata:
      labels:
        app: compcrdwebhook
    spec:
      containers:
      - name: compcrdwebhook
        image: lesterthomas/compcrdwebhook:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443

