apiVersion: v1
kind: Service
metadata:
  name: compcrdwebhook
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    targetPort: 8443
  type: NodePort
  selector:
    app: compcrdwebhook

