deployment:
  compconimage: tmforumodacanvas/component-controller:0.14.0
  secconimage: brianjburton/security-listener:0.5.1
  monitorednamespaces: 'components'           # comma separated list of namespaces
  ingressClass:
    enabled: false
    name: nginx
secret:
  enabled: false
  user: admin
  pass: adpass
configmap:
  #kcbase: http://canvas-keycloak:8088/auth # trying to parameterise this in the configmap
  kcrealm: myrealm
  loglevel: '20'
  